const Plants: {
    id: number,
    name: string
    location: string
}[] = [
    { id: 1, name: "Akat", location: "Tropical and subtropical regions" },
    { id: 2, name: "Agáve americká", location: "Central and South America" },
    { id: 3, name: "Agát bílý", location: "Europe, Asia, North America" },
    { id: 4, name: "Agáve modrá", location: "Mexico" },
    { id: 5, name: "Albizie hedvábná", location: "Tropical and subtropical regions" },
    { id: 6, name: "Aloe vera", location: "Arabian Peninsula, North Africa" },
    { id: 7, name: "Ambrozie peřenokvětá", location: "North America" },
    { id: 8, name: "Ananas obecný", location: "South America" },
    { id: 9, name: "Aralie japonská", location: "East Asia" },
    { id: 10, name: "Arnika horská", location: "Europe, Asia" },
    { id: 11, name: "Bříza bělokorá", location: "Europe, Asia, North America" },
    { id: 12, name: "Buk lesní", location: "Europe" },
    { id: 13, name: "Borůvka obecná", location: "Europe, Asia, North America" },
    { id: 14, name: "Chmel otáčivý", location: "Europe, Asia" },
    { id: 15, name: "Cibule kuchyňská", location: "Central Asia" },
    { id: 16, name: "Dub letní", location: "Europe" },
    { id: 17, name: "Ficus benjamina", location: "Southeast Asia, Australia" },
    { id: 18, name: "Hloh obecný", location: "Europe, Asia, North Africa" },
    { id: 19, name: "Jabloň domácí", location: "Central Asia" },
    { id: 20, name: "Jasan ztepilý", location: "Europe, Asia" },
    { id: 21, name: "Jetel luční", location: "Europe, Asia" },
    { id: 22, name: "Jitrocel větší", location: "Europe, Asia, North Africa" },
    { id: 23, name: "Kaktus", location: "Americas" },
    { id: 24, name: "Kapradina", location: "Worldwide" },
    { id: 25, name: "Kopřiva dvoudomá", location: "Worldwide" },
    { id: 26, name: "Kosatec žlutý", location: "Europe, Asia" },
    { id: 27, name: "Lípa srdčitá", location: "Europe, Asia" },
    { id: 28, name: "Modřín opadavý", location: "Europe, Asia" },
    { id: 29, name: "Narcis", location: "Europe, North Africa" },
    { id: 30, name: "Ořešák vlašský", location: "Balkans, Asia Minor" },
    { id: 31, name: "Pampeliška lékařská", location: "Europe, Asia, North Africa" },
    { id: 32, name: "Pivoňka lékařská", location: "Europe, Asia" },
    { id: 33, name: "Růže šípková", location: "Europe, Asia, North Africa" },
    { id: 34, name: "Smrk ztepilý", location: "Europe" },
    { id: 35, name: "Sněženka", location: "Europe" },
    { id: 36, name: "Třešeň", location: "Europe, Asia" },
    { id: 37, name: "Tulipán", location: "Central Asia" },
    { id: 38, name: "Vrba bílá", location: "Europe, Asia" },
    { id: 39, name: "Vytrvalá čočka", location: "Europe, Asia" },
    { id: 40, name: "Zlatobýl obecný", location: "Europe, Asia, North America" },
    { id: 41, name: "Zlatý déšť", location: "Europe, Asia" },
    { id: 42, name: "Zimostráz vždyzelený", location: "Europe, Asia, North Africa" },
    { id: 43, name: "Borák lékařský", location: "Mediterranean region" },
    { id: 44, name: "Chmel otáčivý", location: "Europe, Asia" },
    { id: 45, name: "Fialka vonná", location: "Europe" },
    { id: 46, name: "Heřmánek pravý", location: "Europe, Asia" },
    { id: 47, name: "Levandule lékařská", location: "Mediterranean region" },
    { id: 48, name: "Máta peprná", location: "Europe, Asia" },
    { id: 49, name: "Rozmarýn lékařský", location: "Mediterranean region" },
    { id: 50, name: "Řebříček obecný", location: "Europe, Asia, North America" }
]


export default Plants